### ISSUE TITLE
suggestion: report the total gas of Etheruem as well and percentages

### ISSUE THREAD

**Issue by sterlingcrispin** [kylemcdonald/ethereum-nft-activity#2] opened 2021-03-09 06:17 UTC
I think it would be great to see what percentage these NFT's are taking up of the total ethereum network -- it could help create some context.

143,595,457,124 is a very big Gas number but what does that mean? Off hand I think Open Sea is something like 0.5-2% of Ethereum's gas usage for the day depending on the day -- you should show how much of the network it's using

**Comment by kylemcdonald** [comment] 2021-03-09 21:41
wow! i didn't realize opensea is even in the whole-percent amounts!

my primary aim for this project is to account for cryptoart's ETH L1 footprint, and not vilify ethereum as a whole or NFTs.

but i'm very open to more context here. i'll leave this issue open so people can find it for now 👌

one possible solution would be a command line option that includes gas percentages (contract gas divided by total daily gas), which is very doable with some small changes.

**Comment by sterlingcrispin** [comment] 2021-03-10 00:38
Even calling this "cryptoart-emissions" is misleading because as far as I understand it, Ethereum would have the same emissions with or without NFTs

**Comment by kylemcdonald** [comment] 2021-03-10 06:10
i was just discussing this point about the "emissions" with joanie, and i agree. i've renamed it "footprint" to highlight that the issue is about a portion of responsibility rather than the direct production of CO2 👌

**Comment by mattdesl** [comment] 2021-03-10 14:45
:+1: Putting these numbers into a larger context is important – many audiences are being led to believe that CryptoArt is 100% to blame for these high annual carbon emissions, but it may be more like 1%. That isn't to diminish the problem, but the scope of the problem should be made clear to the reader. Since you already have a lot of stats here on daily gas of NFT platforms, you can probably quite easily find out the % share they contribute each day to network activity. Without giving this larger context, it simply points the finger at CryptoArt as being the problem, and continues to perpetuate the notion that stopping CryptoArt will somehow stop proof of work cryptocurrencies.

Another thing maybe worth considering is not just showing the entire footprint since these platforms have been created; it would be like showing the entire footprint of McDonald's since it was first started, which is a huge number, and no matter what kind of improvements they make to their footprint in the future, that number will never go down or appear less huge. It also gives the false sense that switching from one platform (OpenSea) to another (Zora) will somehow allow us to escape these footprints, as one has a much smaller footprint than the other. Instead, perhaps it would be better to show these numbers month-over-month, and/or perhaps taking their lifespan and/or size into account, so we can see which ones have a smaller footprint per-capita and/or are making attempts to reduce that footprint each month.

Just my 2c.

**Comment by kylemcdonald** [comment] 2021-03-10 19:50
@mattdesl thank you for your thoughts! as far as i know cryptoart is close to 1% of what ethereum is used for, that sounds correct. this includes long-running NFT projects like cryptokitties.

the total footprint is relevant to work that i'm doing separate from this repo, and i can see how it could feel misleading for someone who is trying to use this data to make a decision about their involvement. for someone who is trying to make a decision about the major platforms, i actually think memo's calculator is the way to go—to get an idea of what footprint of other artists is like.

some things that could be interesting:

* footprint per capita
* footprint per sale
* footprint per month
* footprint per transaction

the last one is not so hard, based on offsetra's 0.000349 kgCO2/gas:

| Name          | kgCO2 per transaction |
|---------------|-----------------------|
| Zora          |                   428 |
| OpenSea       |                   304 |
| SuperRare     |                   189 |
| Foundation    |                   132 |
| Makersplace   |                   109 |
| Nifty Gateway |                    95 |
| Known Origin  |                    85 |
| Rarible       |                    72 |
| Async         |                    69 |

memo reports footprint per sale, i don't know if he reports footprint per capita. footprint per month can be estimated as proportional to volume, available here https://cryptoart.io/data "SuperRare monthly artworks sold" but only for superrare.

**Comment by mattdesl** [comment] 2021-03-10 20:36
Fair enough! Thanks for those details. 

One more consideration would be about the actual footprint metric - kWh per unit of Gas implies that reducing Gas per transaction will somehow help reduce Eth’s annual energy usage/emissions, but I’m not sure that’s the case (happy to be proved wrong). This metric tends to put emphasis on solutions like NFT scaling, lazy minting, etc which can easily make one platform *appear* to be more “energy friendly” than another, but only because of this metric.

Details here:
https://github.com/memo/eco-nft/issues/15#issuecomment-795083905

I realize that’s probably out of scope for whatever you are building here, as you’d like to just use carbonfyi and cryptoartwtf as tools/calculators, but would be curious to get your thoughts on that a well.

**Closed as completed** 2021-03-23 04:07 UTC
